##this file should only contain properties that will OVERRIDE the default properties file.
#Tue Mar 31 05:00:07 UTC 2026
password.encryption-key=EizwwPA8EEfl9dnxh1adOjge6AF0Iza4UxCv6RZhc60\=
mvc.login-success-url=/api-explorer
oauth.client-secret={noop}4ac0bc0d-db16-4956-b864-c06613130b7d
